### ISSUE TITLE
Not functional

### ISSUE THREAD

**Issue by Mikilio** [TheRiceCold/kaizen#3]
Cool Project! I'd like to contribute, by making the nix modules work. Unfortunately, the current commit isn't functional. I'd like to get notified when everything is working again, so I can merge my changes, so I'm leaving this issue here.

**Comment by TheRiceCold** [comment]
Sorry, I made quite a lot of changes and added some new features that are still in progress. I just tested it, and it should be able run now.

I will also update the README with the current features by tomorrow for reference.

**Comment by Mikilio** [comment]
I'll look at it next weekend. Again, thank you for the project.
