### ISSUE TITLE
How does it look now ?

### ISSUE THREAD

**Issue by CMOISDEAD** [TheRiceCold/kaizen#7]
Hello
This is what I get after following the wiki instructions manually, but this doesn't look like the video, does it look like this now ? if so is there any way to get the version you see in the video ?

thanks
![image](https://github.com/user-attachments/assets/3e1f91d9-eba8-4458-a952-2c1b4ac12528)

**Comment by TheRiceCold** [comment]
Sorry for the late response. Yes, that's how it appears; If you prefer the previous statusbar design, I've added an option in the widget settings for `separated` statusbar style.

**Comment by TheRiceCold** [comment]
Here's a video of how things look so far. If you have any suggestions, I'm open to hearing them.

https://github.com/user-attachments/assets/224c3da0-a9f4-4433-af41-1efd1f6a97b3

**Comment by CMOISDEAD** [comment]
Thanks, I love the design

**Comment by CMOISDEAD** [comment]
Thanks, I love the design
